name: progetto-cas
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - OPENROUTESERVICE_API_KEY=${OPENROUTESERVICE_API_KEY}
    restart: always
    networks:
      - internal-network
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - internal-network
  db:
    container_name: db
    image: postgis/postgis:16-3.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
networks:
  internal-network:
    driver: bridge
volumes:
  pgdata: { }