apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: progetto-cas
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000  # porta esterna fissa
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: progetto-cas
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: progetto-cas
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
